### ISSUE TITLE
FWO budget deadline

### ISSUE THREAD

**Issue by georgeskl** [jeanlucb/mla#4]
We need a check somewhere if FWO is among the agencies to check if the found submission date is later than May, so to throw a warning because of budget issues there; check others about their budget deadline (submission before May since then their budget is defined) and corresponding restrictions.

**Comment by jeanlucb** [comment]
Yes, this kind of element is certainly part of the future `FWO_partner_submission()` function in `submission.py`.

**Comment by georgeskl** [comment]
added a condition in the submission if FWO is partner: all possible submission dates whose month is after May are removed from the list of possible submission dates.

**Comment by georgeskl** [comment]
nothing more to add, this has been implemented in agreement with FWO.
